"""empty message

Revision ID: 30e7fe338878
Revises: a09761fc701c
Create Date: 2024-08-18 06:07:02.975001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e7fe338878'
down_revision = 'a09761fc701c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aktuatorji', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('interval', sa.Interval(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Interval(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_activation_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_deactivation_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('sid')
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aktuatorji', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('sid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('last_deactivation_time')
        batch_op.drop_column('last_activation_time')
        batch_op.drop_column('is_active')
        batch_op.drop_column('duration')
        batch_op.drop_column('interval')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
