"""empty message

Revision ID: 4a5a44b7da29
Revises: ec89f84f777b
Create Date: 2024-08-02 08:12:14.560275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5a44b7da29'
down_revision = 'ec89f84f777b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uporabniki', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uporabniki', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
