"""added Settings and ActuatorSetting classes

Revision ID: a09761fc701c
Revises: 4a5a44b7da29
Create Date: 2024-08-14 14:06:36.089122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09761fc701c'
down_revision = '4a5a44b7da29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aktuatorji', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_name', ['name'])

    with op.batch_alter_table('senzorji', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_name', ['name'])

    with op.batch_alter_table('uporabniki', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uporabniki', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')

    with op.batch_alter_table('senzorji', schema=None) as batch_op:
        batch_op.drop_constraint('uq_name', type_='unique')

    with op.batch_alter_table('aktuatorji', schema=None) as batch_op:
        batch_op.drop_constraint('uq_name', type_='unique')

    # ### end Alembic commands ###
